[package]
name = "reverb-daemon"
version = "0.1.0"
description = "Démon Reverb — détient les périphériques et fait tourner la boucle de rendu"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "reverb_daemon"
path = "src/lib.rs"

[[bin]]
name = "reverbd"
path = "src/main.rs"

[dependencies]
reverb-anim = { path = "../reverb-anim" }
reverb-proto = { path = "../reverb-proto" }
reverb-hw = { path = "../reverb-hw" }
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg", "gif"] }
fontdue = { version = "0.9.4", default-features = false, features = ["std"] }

[lints]
workspace = true
